name: Linux

on:
  push:
    branches: [Development]
  pull_request:
    branches: [Development]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.5", "5.6", "5.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: SwiftyLab/setup-swift@v1.5.2
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test