name: Mac-OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.8", "5.9"]
      fail-fast: false
    steps:
      - uses: SwiftyLab/setup-swift@v1.5.2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Build
        run: swift build --build-tests
      - name: Run tests
        run: swift test
