name: MacOS

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:

    macOS-swift55:
        name: macOS (Swift 5.5)
        timeout-minutes: 30
        runs-on: macos-12
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Xcode Version
          run: |
            ls -d /Applications/Xcode*
            sudo xcode-select -s /Applications/Xcode_13.1.app
            xcodebuild -version
            swift --version
        - name: Swift Build
          run: swift build --build-tests
        - name: Swift Test
          run: swift test -Xswiftc -enable-testing